### ISSUE TITLE
Volumes with one or two images fail validation (false "Invalid")

### ISSUE THREAD

**Issue by alexBLR** [emory-libraries/digitizedbooks#2]
Examples in production are here: https://digitizedbooks.library.emory.edu/admin/publish/job/78/
Each is a volume containing one or two images. None of them pass the DigBooks validation algorithm.
The only clue in the logs is "exceptions.AttributeError"
[23/Feb/2017 01:49:58] ERROR:digitizedbooks.apps.publish.models::Error creating KDip 010001334535 : <type 'exceptions.AttributeError'>
jfenton@Kyle-optiplex-9020:/mnt/lsdi2/ftp$ less digbooks.log | grep 010002701475
[15/Feb/2017 02:06:53] ERROR:digitizedbooks.apps.publish.models::Error creating KDip 010002701475 : <type 'exceptions.AttributeError'>
jfenton@Kyle-optiplex-9020:/mnt/lsdi2/ftp$ less digbooks.log | grep 010002701474
[15/Feb/2017 02:06:50] ERROR:digitizedbooks.apps.publish.models::Error creating KDip 010002701474 : <type 'exceptions.AttributeError'>
jfenton@Kyle-optiplex-9020:/mnt/lsdi2/ftp$ less digbooks.log | grep 010002701472
[15/Feb/2017 02:06:46] ERROR:digitizedbooks.apps.publish.models::Error creating KDip 010002701472 : <type 'exceptions.AttributeError'>

**Comment by jkylefenton** [comment]
All kdips in this job https://digitizedbooks.library.emory.edu/admin/publish/job/97/ are affected by this bug.

**Comment by rosy1280** [comment]
pending analysis for next steps.

**Comment by jkylefenton** [comment]
The commonality that I assumed (volumes that only have one or two pages) is now disproven.  Subsequently digitized (recent) 1-2 page items have successfully passed KDip validation.   I just discovered another element these invalid KDips share:  the source images were scanned on an Epson Expression 11000XL flatbed, rather than using the Kirtas machine.   This leads me to believe that something different in the EXIF metadata produced by the flatbed is failing validation, but not in a way such that the web application can give feedback on how to correct the error.   I'll try to analyze the EXIF metadata more closely for clues.

**Comment by rosy1280** [comment]
blocked by @jkylefenton as he investigates exif metadata
